<?php
$a=$_GET["user"];
if($a=="1"){
echo 
'[
{"tp":"images/dm1.jpg","mz":"长沙"},
{"tp":"images/dm2.jpg","mz":"宜章"},
{"tp":"images/dm3.jpg","mz":"莽山"},
{"tp":"images/dm4.jpg","mz":"湘潭"},
{"tp":"images/dm5.jpg","mz":"衡阳"},
{"tp":"images/dm6.jpg","mz":"滨州"},
{"tp":"images/dm7.jpg","mz":"岳阳"},
{"tp":"images/dm8.jpg","mz":"萍乡"},
{"tp":"images/dm9.jpg","mz":"株洲"},
{"tp":"images/dm10.jpg","mz":"明月山"},
{"tp":"images/dm11.jpg","mz":"永州"},
{"tp":"images/dm12.jpg","mz":"娄底"},
{"tp":"images/dm13.jpg","mz":"宜春"},
{"tp":"images/dm14.jpg","mz":"邵阳"},
{"tp":"images/dm15.jpg","mz":"吉安"}
]';
}else if($a=="2"){
echo 
'["全部","云南","四川","浙江",
"山东","江苏","湖南","陕西",
"安徽","西藏","江西","福建",
"广西","青海","贵州","湖北",
"海南","广东","山西","新疆",
"河北","甘肃","河南","黑龙江",
"辽宁","内蒙古","宁夏","吉林"
]';
}
else if($a=="3"){
echo 
'["全部","南极洲","亚洲","欧洲","美洲","非洲","大洋洲"
]';
	}
else if($a=="4"){
echo 
'[
{"tp":"images/gn1.jpg","mz":"北京"},
{"tp":"images/gn2.jpg","mz":"厦门"},
{"tp":"images/gn3.jpg","mz":"上海"},
{"tp":"images/gn4.jpg","mz":"杭州"},
{"tp":"images/gn5.jpg","mz":"南京"},
{"tp":"images/gn6.jpg","mz":"成都"},
{"tp":"images/gn7.jpg","mz":"丽江"},
{"tp":"images/gn8.jpg","mz":"香港"},
{"tp":"images/gn9.jpg","mz":"澳门"},
{"tp":"images/gn10.jpg","mz":"台北"},
{"tp":"images/gn11.jpg","mz":"三亚"},
{"tp":"images/gn12.jpg","mz":"西安"},
{"tp":"images/gn13.jpg","mz":"桂林"},
{"tp":"images/gn14.jpg","mz":"重庆"},
{"tp":"images/gn15.jpg","mz":"青岛"}
]';}
else if($a=="5"){
echo 
'[
{"tp":"images/gat1.jpg","mz":"埃及"},
{"tp":"images/gat2.jpg","mz":"肯尼亚"},
{"tp":"images/gat3.jpg","mz":"南非"},
{"tp":"images/gat4.jpg","mz":"埃塞俄比亚"},
{"tp":"images/gat5.jpg","mz":"纳米比亚"},
{"tp":"images/gat6.jpg","mz":"坦桑尼亚"},
{"tp":"images/gat7.jpg","mz":"毛里求斯"},
{"tp":"images/gat8.jpg","mz":"阿尔及利亚"},
{"tp":"images/gat9.jpg","mz":"摩洛哥"},
{"tp":"images/gat10.jpg","mz":"马达加斯加"},
{"tp":"images/gat11.jpg","mz":"津巴布韦"},
{"tp":"images/gat12.jpg","mz":"安哥拉"},
{"tp":"images/gat13.jpg","mz":"塞舌尔"},
{"tp":"images/gat14.jpg","mz":"塞内加尔"},
{"tp":"images/gat15.jpg","mz":"赞比亚"}
]';}
else if($a=="甘肃"){
echo 
'[
{"tp":"images/gs1.jpg","mz":"陇南","pro":"yunnan"},
{"tp":"images/gs2.jpg","mz":"兰州","pro":"yunnan"},
{"tp":"images/gs3.jpg","mz":"天水"},
{"tp":"images/gs4.jpg","mz":"嘉峪关"},
{"tp":"images/gs5.jpg","mz":"武威"},
{"tp":"images/gs6.jpg","mz":"白银"},
{"tp":"images/gs7.jpg","mz":"平凉"},
{"tp":"images/gs8.jpg","mz":"卓尼"},
{"tp":"images/gs9.jpg","mz":"山丹"},
{"tp":"images/gs10.jpg","mz":"临泽"},
{"tp":"images/gs11.jpg","mz":"玉门"},
{"tp":"images/gs12.jpg","mz":"会宁"}
]';}
?>