<?php
$a=$_GET["user"];
if($a=="1"){
echo 
'["房型预订",
"位置交通",
"设施概况",
"点评问答",
"如何返现"
]';
}
if($a=="2"){
echo 
'[
	{"tp":"images/kh1.jpg","tb1":"images/srz.png","fjm":"温馨园景大床房","li":"images/li.png",
	"wz":"面积60㎡位于7层有窗","zx":"images/zx.jpg","jj":"温馨园景大床房( 享携程拼车接机 )","dj":"images/dj.png",
	"tb2":"images/srz.png","zc":"无早","qx":"取消扣全款","jg":120,"mj":"¥126减¥6"},
	{"tp":"images/kh2.jpg","tb1":"images/srz.png","fjm":"舒适园景大床房","li":"images/li.png",
	"wz":"面积60㎡位于7层有窗","zx":"images/zx.jpg","jj":"舒适园景大床房","dj":"images/dj.png",
	"tb2":"images/srz.png","zc":"无早","qx":"取消扣全款","jg":138,"mj":"¥138减¥8"},
	{"tp":"images/kh3.jpg","tb1":"images/srz.png","fjm":"精致园景大床房","li":"images/li.png",
	"wz":"面积60㎡位于7层有窗","zx":"images/zx.jpg","jj":"精致园景大床房( 享携程拼车接机 )","dj":"images/dj.png",
	"tb2":"images/srz.png","zc":"无早","qx":"取消扣全款","jg":150,"mj":"¥153减¥3"},
	{"tp":"images/kh4.jpg","tb1":"images/srz.png","fjm":"温馨两房一厅套房","li":"images/li.png",
	"wz":"面积60㎡位于7层有窗","zx":"images/zx.jpg","jj":"温馨两房一厅套房","dj":"images/dj.png",
	"tb2":"images/srz.png","zc":"无早","qx":"取消扣全款","jg":220,"mj":"¥220减¥20"},
	{"tp":"images/kh5.jpg","tb1":"images/srz.png","fjm":"精致两房一厅套房","li":"images/li.png",
	"wz":"面积60㎡位于7层有窗","zx":"images/zx.jpg","jj":"精致两房一厅套房( 享携程拼车接机 )","dj":"images/dj.png",
	"tb2":"images/srz.png","zc":"无早","qx":"取消扣全款","jg":170,"mj":"¥180减¥10"},
	{"tp":"images/kh6.jpg","tb1":"images/srz.png","fjm":"海景两房一厅套房","li":"images/li.png",
	"wz":"面积60㎡位于7层有窗","zx":"images/zx.jpg","jj":"海景两房一厅套房( 享携程拼车接机 )","dj":"images/dj.png",
	"tb2":"images/srz.png","zc":"无早","qx":"取消扣全款","jg":180,"mj":"¥186减¥6"}
]';
}if($a=="3"){
echo 
'[
{"jccz":"机场车站"},
{"tp":"images/jz1.png","zm":"凤凰机场","lx":"行车约12分钟，距离约5.4公里"},
{"tp":"images/jz2.png","zm":"三亚站","lx":"行车约16分钟，距离约7.9公里"},
{"tp":"images/jz3.png","zm":"三亚汽车总站","lx":"行车约29分钟，距离约10.5公里"},
{"tp":"images/jz3.png","zm":"三亚汽车站","lx":"行车约12分钟，距离约5.4公里"},
{"jtxx":"查看全部交通信息"}
]';
}if($a=="4"){
echo 
'[
{"tp":"images/tx1.png","yhm":"rdon9680","dpxs":"点评新手","ps":"1篇点评","pj":"老板人很好，很热情",
"fw":"images/fw.png","wz":"经由去哪儿网预订","nr":"老板人很好，很热情，服务态度很赞，还给我们免费升级为海景房，住的地方很干净，周围环境很适合，接近海滩，而且住的地方对面就有超市，附近也有吃的地方，交通也挺便利，我们自驾游过去，老板还带我们去停车，五星好评","shu":["images/xt1.jpg","images/xt2.jpg","images/xt3.jpg","images/xt4.jpg","images/xt5.jpg","images/xt6.jpg"],"lz":"来自去哪儿客户端","shu1":["images/dt1.jpg","images/dt2.jpg","images/dt3.jpg","images/dt4.jpg","images/dt5.jpg","images/dt6.jpg"]},
{"tp":"images/tx2.png","yhm":"povq1327","dpxs":"点评新手","ps":"1篇点评","pj":"前台服务也很周到热情",
"fw":"images/fw.png","wz":"经由去哪儿网预订","nr":"公寓整体环境非常好，房间内部设施齐全，床铺整洁干净，装修风格简约时尚，住着非常舒服，前台服务也很周到热情，交通也很方便，值得推荐！独自旅行2018年10月入住","shu":"","lz":"来自去哪儿客户端"},
{"tp":"images/tx3.png","yhm":"povq1327","dpxs":"点评新手","ps":"1篇点评","pj":"空气清新,交通也很方便,卫生特别整洁","fw":"images/fw.png","wz":"经由去哪儿网预订","nr":"住在这里环境优美，空气清新，交通也很方便，卫生特别整洁，主要是房子各个角落都非常干净，住着也特别放心，给满分!独自旅行2018年10月入住","shu":"","lz":"来自去哪儿客户端"},
{"tp":"images/tx4.png","yhm":"povq1327","dpxs":"点评新手","ps":"1篇点评","pj":"公寓的房间进门给人一种家的感觉","fw":"images/fw.png","wz":"经由去哪儿网预订","nr":"公寓的房间进门给人一种家的感觉，干净，整齐，让人十分舒服，服务态度亲切，交通便利，有机会再次来三亚旅行还会来入住!家庭出行2018年10月入住","shu":"","lz":"来自去哪儿客户端"},
{"tp":"images/tx5.png","yhm":"povq1327","dpxs":"点评新手","ps":"1篇点评","pj":"首先前台服务特别好","fw":"images/fw.png","wz":"经由去哪儿网预订","nr":"首先前台服务特别好，有什么需要都能耐心解答帮忙，住的地方交通也便利，出去玩总是来回奔波，住的舒心方便真的省了不少心。另外住的房间很安静干净，没有什么异味，总之挺不错的，会推荐给朋友们的夫妻/情侣2018年08月入住","shu":"","shu":["images/xt7.jpg","images/xt8.jpg","images/xt9.jpg","images/xt10.jpg","images/xt11.jpg","images/xt12.jpg"],"lz":"来自去哪儿客户端","shu1":["images/dt7.jpg","images/dt8.jpg","images/dt9.jpg","images/dt10.jpg","images/dt11.jpg","images/dt12.jpg"]},
{"tp":"images/tx6.png","yhm":"povq1327","dpxs":"点评新手","ps":"1篇点评","pj":"前台服务也很周到热情,交通也很方便","fw":"images/fw.png","wz":"经由去哪儿网预订","nr":"酒店地理位置好，环境优美，交通便利，房间舒适，服务人员很热情，乐于提供各种帮助。。设施很人性化，网络速度快，下次还会去住!其他2018年08月入住","shu":"","lz":"来自去哪儿客户端"}
]';
}
?>